### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by Cousken** [jazzmind/steamcsv#1]
I tried using this tool, but when i pressed the Export button, nothing happened. 

This is the error message i get in the console of my web browser ( firefox ) 

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=[removed]&steamid=[removed]format=json&include_appinfo=1. This can be fixed by moving the resource to the same domain or enabling CORS.

The [removed] tags are my account and other personal information :)

**Comment by jazzmind** [comment]
Hi - I added info in the readme that helps get around this. Basically it's a browser security feature you need to disable. The security feature prevents a script that comes from one site to make an ajax call to another site. I use the chrome extension so I can turn it on/off easily... however it's more secure to use a different launcher since who knows what's in the extension!
